### ISSUE TITLE
The site is no longer working

### ISSUE THREAD

**Issue by rpique** [konradjk/Interpretome#2]
The links to where this tool was running do not seem to work anymore:
http://genotation.stanford.edu/
The wiki also does not seem to be active:
http://esquilax.stanford.edu/wiki

I have used this a few times in a genetic class to teach a few concepts. It was very useful. Do you think the server could be restored again? I could also try to implement it at my own site if that would be ok?

**Comment by konradjk** [comment]
Yes, unfortunately we did not have funding to keep the server going. You are absolutely welcome to re-implement it at your own site and use our code here (note that it relies on some SQL databases which I no longer have access to, so you will have to rebuild them from scratch, or possibly modify them to more modern data).

**Comment by rpique** [comment]
Thank you very much for the reply. I totally understand. I was using it for a class and it was a very nice tool for teaching. It may take some time for me to rebuild the databases without a template, but I may give it a try.

**Comment by jnton** [comment]
@rpique any news? It's a pity that Interpretome/Genotation no longer works :(

**Comment by jnton** [comment]
Btw @konradjk is [this](https://www.genotation.com/) an official re-implementation of GENOtation? It seems that it is made by Stuart Kim (he was a Professor at Stanford University).
